# Generated by Django 2.0.6 on 2018-06-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_auto_20180617_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordprogress',
            name='interval',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
