# Generated by Django 2.0.6 on 2018-06-17 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_auto_20180617_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordprogress',
            name='last_review',
        ),
    ]
