# Generated by Django 2.0.6 on 2018-06-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_article_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='language',
            field=models.CharField(default='de', max_length=8),
            preserve_default=False,
        ),
    ]
